name: 'PagerDuty Send Event/Alert'
description:
  'Send an event to PagerDuty to trigger, acknowledge, or resolve incidents.'
author: 'acyphus'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
