name: 'PagerDuty Send Event/Alert'
description:
  'Send an event to PagerDuty to trigger, acknowledge, or resolve incidents.'
author: 'acyphus'

# Define your inputs here.
inputs:
  pagerDutyRoutingKey:
    description: 'The PagerDuty Integration Key.'
    required: true
  dedupKey:
    description:
      'Identifies the alert to trigger, acknowledge, or resolve. Required unless
      the event_type is trigger.'
    required: false
  eventAction:
    description: 'The type of event. Can be trigger, acknowledge or resolve.'
    required: true
    default: 'trigger'
  summary:
    description:
      'A brief text summary of the event, used to generate the summaries/titles
      of any associated alerts.'
    required: true
    default: 'Alert from ${ownerName}/${repoName} by ${actor}'
  source:
    description: 'The unique location of the affected system.'
    required: false
    default: 'GitHub Actions in ${ownerName}/${repoName}'
  severity:
    description:
      'The perceived severity of the status the event is describing with respect
      to the affected system.. Can be info, warning, error, or critical.'
    required: true
    default: 'critical'
  clientUrl:
    description:
      'The URL of the monitoring client that is triggering this event. (This
      field is only used for trigger events.)'
    required: false
    default: 'https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}'

# Define your outputs here.
outputs:
  time:
    description: 'Timestamp of the event.'

runs:
  using: node20
  main: dist/index.js
