# Unordered list style
MD004:
  style: dash

# Line length
MD013: false

# Ordered list item prefix
MD029:
  style: one_or_ordered

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Code block style
MD046:
  style: fenced
